#!/bin/bash

# install packages we always want
if [ $(command -v pacman) ]; then
  sudo pacman -Syu --noconfirm
  sudo pacman -S --noconfirm zsh git stow tmux
elif [ $(command -v yum) ]; then
  yum install -y epel-release
  yum update -y
  yum install -y zsh git stow tmux cmake
elif [ $(command -v apt-get) ]; then
  sudo apt update -y
  sudo apt upgrade -y
  sudo apt install -y zsh git stow tmux
else
  echo "No valid package manager found"
  exit 1
fi

# Clone zgen
git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"

# Clone dotfiles
git clone https://github.com/alextes/dotfiles.git

# Setup tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
sh ~/.tmux/plugins/tmp/scripts/install-plugins.sh

# Stow things
cd ${HOME}/dotfiles
stow git scripts zsh
if [ ${ENV:='SERVER'} == 'SERVER' ]; then
  stow vim-server
else
  stow vim
fi
cd ${HOME}

# base16
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
.config/base16-shell/scripts/base16-default-dark.sh

# Install vim plugins
git clone git://github.com/chriskempson/base16-vim.git ~/.vim/colors/base16
cp ~/.vim/colors/base16/colors/*.vim ~/.vim/colors
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall
mkdir ${HOME}/.vimundo

# Set shell
chsh -s $(which zsh)
exec zsh
