#!/bin/bash

BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
[ -s "$BASE16_SHELL/profile_helper.sh" ] && \
eval "$("$BASE16_SHELL/profile_helper.sh")"

COLOR_SCHEMES=$(cat ~/knowledge/base16-colors.md | grep \* | cut -d' ' -f2)
BASE_16_SCHEME=$(echo "$COLOR_SCHEMES" | sort --random-sort | head -n 1)

ln -sf ~/.config/base16-shell/scripts/${BASE_16_SCHEME}.sh ~/.base16_theme
source ~/.config/base16-shell/scripts/${BASE_16_SCHEME}.sh
