#!/bin/bash

set -e

ENV=$1

if [[ $ENV == "staging" || $ENV == "stag" ]]; then
    PREFIX="stag"
elif [[ $ENV == "prod" || $ENV == "production" ]]; then
    PREFIX="prod"
else
    PREFIX="stag"
fi

LAST_VERSION=$(git tag | grep "$PREFIX-v" | cut -c 7- | sort -n -r | head -n 1)
NEXT_VERSION=$(( $LAST_VERSION + 1))
CURRENT_COMMIT=$(git rev-parse --short HEAD)
TAG="$PREFIX-v$NEXT_VERSION"
git tag "$TAG"
echo "tagged commit $CURRENT_COMMIT, as $TAG"

git push
sleep 4
git push --tags
sleep 10

echo $(hub ci-status)

while [[ $(hub ci-status) == "pending" ]]; do
    clear
    hub ci-status --verbose || :
    sleep 10
done

echo "done deploying $TAG"
osascript -e "display notification \"done deploying $TAG\""
