#!/bin/sh

set -e

# For some reason our github build step outputs frontend images with a docker tag with seven characters even if the commits have eight.
SHORT_SHA=$(git rev-parse --short HEAD | cut -c-7)
CURRENT_DIR=$(pwd)
CURRENT_PROJECT=$(pwd | cut -d '/' -f 6)
OLD_IMAGE="rg.fr-par.scw.cloud\/ultrasoundmoney\/$CURRENT_PROJECT.*"
NEW_IMAGE="rg.fr-par.scw.cloud\/ultrasoundmoney\/$CURRENT_PROJECT:$SHORT_SHA"

cd ~/code/usm/infra/base

sed -i '' "s/$OLD_IMAGE/$NEW_IMAGE/g" ./*.yaml

cd ~/code/usm/infra/overlays/dev

sed -i '' "s/$OLD_IMAGE/$NEW_IMAGE/g" ./*.yaml

cd ~/code/usm/infra/overlays/prod

sed -i '' "s/$OLD_IMAGE/$NEW_IMAGE/g" ./*.yaml

cd $CURRENT_DIR
