#!/bin/sh
read -p "Are you sure? [y/n]" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "restarting master#1 3dhubs-production-003"
  ssh -i ~/.ssh/3dhubs-amsterdam.pem ubuntu@52.208.14.234 'sudo service elasticsearch restart'
  echo "sleeping 30s"
  sleep 30
  echo "restarting master#2 3dhubs-production-002"
  ssh -i ~/.ssh/3dhubs-amsterdam.pem ubuntu@52.49.196.64 'sudo service elasticsearch restart'
  echo "sleeping 30s"
  sleep 30
  echo "restarting master#3 3dhubs-production-001"
  ssh -i ~/.ssh/3dhubs-amsterdam.pem ubuntu@52.209.64.81 'sudo service elasticsearch restart'
  echo "done"
fi

